BCIT-SSD-2020-21/indigenous-plant-go-cms

- README.md
> Ap02readme

- planning/server/api/audio_files/DELETE_audio_file.jsonc
- planning/server/api/audio_files/GET_audio_file.jsonc
- planning/server/api/audio_files/POST_audio_file.jsonc
- planning/server/api/audio_files/PUT_audio_file.jsonc
- planning/server/api/images/DELETE_image.jsonc
- planning/server/api/images/GET_image.jsonc
- planning/server/api/images/POST_image.jsonc
- planning/server/api/images/PUT_image.jsonc
- planning/server/api/videos/DELETE_video.jsonc
- planning/server/api/videos/GET_video.jsonc
- planning/server/api/videos/POST_video.jsonc
- planning/server/api/videos/PUT_video.jsonc
- server/mongoDatabase.js
Closes #53 
Create now require their respective file field as well as a caption field
Closes #52 
The api route is now added to /planning/server/api
> DocAndFixes

- server/jwt.js
- server/routers/pingRouter.js
- server/routers/usersRouter.js
- server/server.js
Closes #68 
Now they return an object with accessToken and user property.
accessToken contains the jwt token as string.
user contains the object of user with _id, email, username, role
Closes #69 
A route with the following
GET /api/ping
Just send a GET request with the token as the bearer token to here and it will either respond with 200 for success or 501 for error.
> 68&69Return stuff for login register

- server/seeder.js
> Seeder Script

- server/mongoDatabase.js
- server/server.js
Changes to make deployment work
> DeploymentChanges

- database/seeder.js
> Ap96addtour

- planning/server/api/plants/DELETE_plant.md
- planning/server/api/plants/GET_plant.md
- planning/server/api/plants/PUT_plant.md
- server/mongoDatabase.js
- server/routers/waypointsRouter.js
- server/server.js
Closes #105 
Waypoint CRUD with some other changes including:
Changing get for plant to take from audio_files instead of audios.
Remainder of the plant documentation.
Still need to do the waypoint documentation, will do that together with tour route.
> 105WaypointRoute

- server/jwt.js
- server/mongoDatabase.js
Make JWT token expire.
Change location to take longitude and latitude instead of coordinate.
> LocationFieldChange

- server/mongoDatabase.js
Fix some aggregate function issue.
> UnwindBugFix

- server/mongoDatabase.js
Closes #116 
One thing to note is that if there is no plant data for example it will still return an object of empty array due to the effect of unwind and group.
I don't really know how to fix that though.
> 116ExpandDataInGet

- planning/server/api/users/GET_users.md
- server/mongoDatabase.js
- server/routers/usersRouter.js
- server/server.js
Closes #143 
GET /api/users
Get all user (without password)
Currently I set it to take in api key, not sure if needed
> 143GetUsersRoute

- planning/server/api/learn_more/DELETE_learn_more.md
- planning/server/api/learn_more/GET_learn_more.md
- planning/server/api/learn_more/GET_learn_mores.md
- planning/server/api/learn_more/POST_learn_more.md
- planning/server/api/learn_more/PUT_learn_more.md
Learn more uses erd as reference on what to take in.
> LearnMoreDocumentation

- server/jwt.js
Change from expiring in 1 hr -> 1 day
> JWTTokenExpireTimeChange

- planning/server/api/users/GET_user.md
- server/mongoDatabase.js
- server/routers/usersRouter.js
Closes #149
GET /api/users/:userId
Takes the api key for now.
> 149GetOneUserRoute

- planning/server/api/users/GET_user.md
- planning/server/api/users/GET_users.md
- planning/server/api/users/RESETPASSWORD.md
- server/mongoDatabase.js
- server/package-lock.json
- server/package.json
- server/routers/usersRouter.js
Closes #86 
POST /api/users/reset_password
This function takes an email and reset the password
> 86ResetPassword

- server/mongoDatabase.js
Closes #161 
These changes affect plants, waypoints, tours, and learn_more.
This is one part of the type validation which ensures the following:
What needs to be array is actually array.
Closes #170 
Affects waypoints.
Location objectId is now locations array of objectId.
Closes #171 
Cut down in how deep the aggregation expands but fix the issue regarding plants not being array on get.
> TypeValidationAndWaypointFixes

- server/mongoDatabase.js
This is one of the waypoint issue which is there being duplicate plant in plants when new plant is added on.
> FixDuplicateIssue

- server/mongoDatabase.js
The other issue is covered in #178 
Closes #176 
Fix plants field in waypoint, also did it in tours.
May need to figure out removing deleted plants from waypoints in the database later but it shouldn't affect what the api returns.
> 176FixPlantsFieldInWaypoint

- planning/server/api/plants/GET_ALL_plants.md
- planning/server/api/plants/GET_plant.md
- planning/server/api/plants/POST_plant.md
- planning/server/api/plants/PUT_plant.md
- planning/server/api/waypoints/GET_ALL_waypoints.md
- planning/server/api/waypoints/GET_waypoint.md
- planning/server/api/waypoints/POST_waypoint.md
- planning/server/api/waypoints/PUT_waypoint.md
- server/mongoDatabase.js
- server/routers/plantsRouter.js
- server/routers/waypointsRouter.js
Closes #192 
Briefly going over this:
Previous get all route for plants and waypoints now only get published plants and waypoints.
GET /api/plants
GET /api/waypoints
To get all plants and waypoints, new route is added.
GET /api/plants/all
GET /api/waypoints/all
These will show the isPublish field as well.
Plants in waypoints are not hidden base on the isPublish status.
> 192AddIsPublishField

- planning/server/api/videos/POST_video.md
- planning/server/api/videos/PUT_video.md
- server/mongoDatabase.js
- server/routers/videosRouter.js
Closes #196 
Now it takes input "video_url" follow by the youtube url instead of the old "video".
> 196ChangeVideoToTakeYoutubeUrlInsteadOfVideoFile

- planning/server/api/plants/POST_plant.md
- planning/server/api/plants/PUT_plant.md
- planning/server/api/waypoints/POST_waypoint.md
- planning/server/api/waypoints/PUT_waypoint.md
- server/mongoDatabase.js
Closes #208 
Does as the issue says, the error message is documented in the usual place.
Also modify a potential bug regarding using the standard falsey check.
> 208MakeLocationRequired

- planning/launch.md
Closes #219 
This covers how to run client side of cms locally.
> 219LocalClientSideLaunchDocumentation
